database:
  use: SQL # LOCAL(local...),SQL
  sql:
    host: 127.0.0.1
    port: 3306
    user: root
    password: 123456
    database: bukkit_plugin
    table: planners_v2

settings:
  # 自定义伤害类型（防止拼写错误）
  damage-causes:
    - SKILL
    - ATTRIBUTE
    - MYTHIC
  placeholder:
    # 使用模式, script, literal
    use: script
  attack:
    # 攻击保护，如果开启后无法在某些场景下攻击，这取决于插件的实现
    protect:
      enable: true
      # 应用场景
      scene:
        - world xxx
        - dungeonplus *
        - team *
        - worldguard xxx
  magic-point:
    resume:
      # 法力值的恢复的运算表达式
      expression: "1 + Math::random(1, 2)"
      # 法力值的恢复的更新任务的轮询周期,单位tick
      update-tick: 20
    upper-limit:
      # 法力值的运算表达式
      # 可用函数:
      #   &profile :: level() - 玩家等级
      #   &profile :: magicPoint() - 当前魔力值
      #   &ctx :: level() - 技能等级 (技能脚本中)
      expression: "&profile :: level() * 2 + 100"
      # 最大法力值的更新任务的轮询周期,单位tick
      update-tick: 20
  level:
    # 同步原版等级
    synchronize: true
    # 原版经验求兼容
    original-hook: true
    # 等级隔离
    # all = 全职业统一
    # router = 职业路线独立
    # job = 职业独立
    isolation: all
    # 当 isolation 为 all 时,该选项生效
    algorithm: def0
  cooler:
    use: memory
  minecraft:
    interaction-action:
      enable: false
      empty-skill:
        material: STONE
        name: '空技能 | 待学习'
  bukkit-launch:
    unimpeded-types:
      - AIR
      - SHORT_GRASS
      - GLASS
      - WATER
      - DANDELION
